- name: get token gitlab
  hosts: all
  gather_facts: false

  tasks:
  - name: Wait gitlab token
    ansible.builtin.wait_for:
      path: /etc/gitlab/initial_root_password
      connect_timeout: 5
      delay: 2  
  - name: Cat token git lab
    ansible.builtin.shell: |
      cat /etc/gitlab/initial_root_password
    register: file_content
    become: yes
  - name: Set fact token
    ansible.builtin.set_fact:
      token: "{{ file_content.stdout | regex_search(token_re, '\\1') | first }}"
    vars:
      token_re: 'Password:\s(\S+)'
  - name: Create file
    ansible.builtin.template:
      src: ./token.j2
      dest: ../gitlab/token_gitlab
    delegate_to: localhost      