- name: deploy atlantis
  hosts: all
  gather_facts: false

  tasks:
  - name: Install package
    ansible.builtin.apt:
      name:
        - unzip
        - python3-pip
        - git
      update_cache: yes
    become: yes
  - name: Install ansible
    ansible.builtin.pip:
      name: ansible-core<2.13
      executable: pip3
    become: yes
  - name: Install collection general
    ansible.builtin.shell: ansible-galaxy collection install community.general
    become: yes
  - name: Install collection posix
    ansible.builtin.shell: ansible-galaxy collection install ansible.posix
    become: yes    
  - name: Get Atlantis
    ansible.builtin.unarchive:
      src: https://github.com/runatlantis/atlantis/releases/download/v0.24.2/atlantis_linux_amd64.zip
      dest: /usr/bin
      remote_src: yes
    become: yes
  - name: Copy terraform
    ansible.builtin.copy:
      src: /usr/local/bin/terraform
      dest: /usr/bin/terraform
      mode: '0755'
    become: yes
  - name: Copy atlantis service 
    ansible.builtin.copy:
      src: ./atlantis_service
      dest: /etc/systemd/system/atlantis.service
      mode: '0755'
    become: yes
  - name: Copy atlantis config 
    ansible.builtin.copy:
      src: ./atlantis_config.yaml
      dest: /home/pugachevvv/atlantis_config.yaml
      mode: '0755'
  - name: Copy atlantis config repos
    ansible.builtin.copy:
      src: ./atlantis_repos.yaml
      dest: /home/pugachevvv/repos.yaml
      mode: '0755'
  - name: Copy terraformrc
    ansible.builtin.copy:
      src: /home/pugachevvv/.terraformrc
      dest: /root/.terraformrc
      mode: '0755'
    become: yes
  - name: run atlantis
    ansible.builtin.systemd:
      state: started
      name: atlantis
    become: yes
  - name: allow tcp 4141
    ansible.builtin.iptables:
      chain: INPUT
      jump: ACCEPT
      protocol: tcp
      match:
        - tcp
      destination_port: 4141
    become: yes