---
imagePullPolicy: IfNotPresent
gitlabUrl: http://51.250.69.185
runnerRegistrationToken: "GR1348941sD2yK1F8YU8xDLsJCs6k"
terminationGracePeriodSeconds: 3600
concurrent: 10
checkInterval: 30
sessionServer:
 enabled: false
rbac:
  create: true
  clusterWideAccess: true
  podSecurityPolicy:
    enabled: false
    resourceNames:
      - gitlab-runner
runners:
  config: |
    [[runners]]
      tags = "devlever"
      [runners.kubernetes]
        namespace = "{{.Release.Namespace}}"
        image = "ubuntu:20.04"
        privileged = true
        name = "runner-dev"
        [[runners.kubernetes.volumes.secret]]
          name = "regcred"
          mount_path = "/root/.docker"
          read_only = true
          [runners.kubernetes.volumes.secret.items]
              ".dockerconfigjson" = "config.json"
