cloud_id="${cloud_id}"
admin_bgw_external_ip = "${admin_bgw_external_ip}"
admin_bgw_internal_ip = "${admin_bgw_internal_ip}"
service_account_key_file = "./admin-resourse-env-${workspace}.json"
folder_id= "${folder_id}"
