apiVersion: apps/v1
kind: Deployment
metadata:
  name: web
spec:
  replicas: 1
  selector:
    matchLabels:
      app: web
  template:
    metadata:
      labels:
        app: web
    spec:
      containers:
        - env:
          - name: AccessKeyID
            valueFrom:
              secretKeyRef:
                name: webapp
                key: access_key
          - name: SecretAccessKey
            valueFrom:
              secretKeyRef:
                name: webapp
                key: secret_key
          image: cr.yandex/crprsbkmreld0gpt1k7q/web_app:fc54edaf
          ports:
            - containerPort: 8080
          imagePullPolicy: Always
          name: web
      imagePullSecrets:
        - name: regcred